### PR TITLE
fix: handled case where event handler removed inside handler

### LINKED ISSUE #125: events not called when removeListener used inside callback
Im creating 2 separate message handlers for the same topic.
inside the first message handler it removes itself via removeListener() to imitate a once() call:
```
const mqEmitter = require('mqemitter');

function messageHandler1 (message, cb) {
  console.log('messageHandler1 called');
  // removes itself
  mqEmitter.removeListener('hello', messageHandler1);
  cb();
}

e.on('hello', messageHandler1)

function messageHandler2 (message, cb) {
  console.log('messageHandler2 called');
  cb();
}

mqEmitter.on('hello', messageHandler2);

mqEmitter.emit({ topic: 'hello' }, function () {
  console.log('emit callback called');
});
```
I would expect both of the handlers to be called and after that the emit callback.
so the expected output should be:
```
messageHandler1 called
messageHandler2 called
emit callback called
```
the second callback and the emit callback are newver called and the actual output is:
```
messageHandler1 called
```

I think the issue is that when emitting, fastparallel is given the same array instance that is used to hold (and remove for that matter) message handlers here: https://github.com/mcollina/mqemitter/blob/master/mqemitter.js#L121

### PR DESCRIPTION
**Pull request by john-dagger**
fixes #125

### CODE REVIEW

File: mqemitter.js [hunk 1]
```diff
@@ -118,7 +118,7 @@ MQEmitter.prototype._do = function (message, callback) {
   const matches = this._matcher.match(message.topic)
 
   this.current++
-  this._parallel(this, matches, message, callback)
+  this._parallel(this, Array.from(matches), message, callback)
```
Comment (mcollina) [inline mqemitter.js:121]: I have a feeling that Array.from is slower than allocating an array of the same size and then use an old school `for (;;)` to copy over.

File: mqemitter.js [hunk 2]
```diff
@@ -116,9 +116,14 @@ MQEmitter.prototype.close = function close (cb) {
 MQEmitter.prototype._do = function (message, callback) {
   this._doing = true
   const matches = this._matcher.match(message.topic)
+  const matchesCopy = new Array(matches.length)
+  for (let i = 0, len = matches.length; i < len; i++) {
+    matchesCopy[i] = matches[i]
+  }
```
Comment (mcollina) [inline mqemitter.js:122]: This will add too much overhead. Let's do the reverse: whenever `removeListener()` is called, a new array is allocated.

**Review by mcollina — CHANGES_REQUESTED** [review]

File: mqemitter.js (hunk 2 above)
Comment (john-dagger) [reply mqemitter.js:122]: ok seems fair,
Im not sure how we'd implement that, because the array with the matched handlers is given to fastparallel in `_do()`
and the `removeListener()` is called within a matched handler that was called by fastparallel?

Comment (mcollina) [reply mqemitter.js:122]: Actually there is a better way: move the removal inside a setImmediate.

File: mqemitter.js [hunk 3]
```diff
@@ -74,12 +74,13 @@ MQEmitter.prototype.on = function on (topic, notify, done) {
...
-
-  if (done) {
-    setImmediate(done)
-  }
-
+  const that = this
+  setImmediate(function () {
+    that._matcher.remove(topic, notify)
+    if (done) {
+      setImmediate(done)
```
Comment (mcollina) [inline mqemitter.js:81]: No need for the additional setImmediate here

**Review by mcollina — APPROVED** [review]
lgtm
